candidates/urls.py
from django.urls import path

from . import views as v

app_name = 'candidates'
urlpatterns = [
    path('', v.index, name='index'),
    path('create/', v.create, name='create'),
    path('<int:pk>/', v.show, name='show'),
    path('<int:pk>/edit/', v.edit, name='edit'),
    path('<int:pk>/delete/', v.delete, name='delete'),
    path('<int:pk>/vote/', v.vote, name='vote'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import root

urlpatterns = [
    path('', root, name='root'),
    path('candidates/', include('candidates.urls')),
    path('admin/', admin.site.urls),
]

candidates/models.py
from django.db import models


class Candidate(models.Model):
    first_name = models.CharField('名字', max_length=10)
    last_name = models.CharField('姓氏', max_length=10)
    age = models.PositiveSmallIntegerField('年紀')
    politics = models.TextField('政見', max_length=300)
    vote = models.PositiveIntegerField('得票數', default=0)

    def __str__(self):
        return self.full_name()

    def full_name(self):
        return '{} {}'.format(self.last_name, self.first_name)

candidates/forms.py
from core.forms import BootstrapModelForm

from .models import Candidate


class CandidateModelForm(BootstrapModelForm):
    class Meta:
        model = Candidate
        fields = ['last_name', 'first_name', 'age', 'politics']

core/forms.py
from django.forms import ModelForm


class BootstrapModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': '請輸入{}'.format(self.fields[field].label)
            })

candidates/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.messages import add_message as m, SUCCESS, ERROR

from .models import Candidate
from .forms import CandidateModelForm


def index(request):
    candidates = Candidate.objects.all()
    return render(request, 'candidates/index.html', {'candidates': candidates})


def show(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    return render(request, 'candidates/show.html', {'candidate': candidate})


def create(request):
    form = CandidateModelForm(request.POST or None)
    if form.is_valid():
        candidate = form.save()
        m(request, SUCCESS, 'Create success')
        return redirect('candidates:show', candidate.id)

    return render(request, 'candidates/create.html', {'form': form})


def edit(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    form = CandidateModelForm(request.POST or None, instance=candidate)
    if form.is_valid():
        form.save()
        m(request, SUCCESS, 'Edit success')
        return redirect('candidates:show', pk)

    return render(request, 'candidates/edit.html', {'form': form})


def delete(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    if request.method == 'POST':
        candidate.delete()
        m(request, SUCCESS, 'Delete success')
        return redirect('candidates:index')

    return render(request, 'candidates/delete.html', {'candidate': candidate})


def vote(request, pk):
    if request.method == 'POST':
        candidate = get_object_or_404(Candidate, pk=pk)
        candidate.vote += 1
        candidate.save()
        m(request, SUCCESS, 'Vote success')
    else:
        m(request, ERROR, 'Vote error')

    return redirect('candidates:index')

core/views.py
from django.shortcuts import redirect


def root(request):
    return redirect('candidates:index')

candidates/templates/candidates/create.html
{% extends 'base.html' %}

{% block body %}
  <div class="row">
    <div class="col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h1>Create candidates</h1>
      <hr>
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

candidates/templates/candidates/delete.html
{% extends 'base.html' %}

{% block body %}
  <div class="row">
    <div class="col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>Delete candidates</h2>
      <hr>
      <p>Are you sure to delete candidates {{ candidate.full_name }}?</p>
      <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-danger">Yes</button>
        <a href="{% url 'candidates:show' candidate.id %}" class="btn btn-sm btn-secondary">No</a>
      </form>
    </div>
  </div>
{% endblock %}

candidates/templates/candidates/edit.html
{% extends 'base.html' %}

{% block body %}
  <div class="row">
    <div class="col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h1>Edit candidates</h1>
      <hr>
      {% include '_form.html' %}
    </div>
  </div>
{% endblock %}

candidates/templates/candidates/index.html
{% extends 'base.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <h1>
        Candidates list
        <a href="{% url 'candidates:create' %}" class="btn btn-success float-right">Create</a>
      </h1>
      <div class="modal fade" id="vote-modal" tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <form action="" method="post">
              {% csrf_token %}
              <div class="modal-header">
                <h5 class="modal-title" id="modal-label">Vote confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p id="confirm-label"></p>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Vote</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for candidate in candidates %}
            <tr>
              <td scope="row">{{ candidate.id }}</td>
              <td><a href="{% url 'candidates:show' candidate.id %}">{{ candidate.full_name }}</a></td>
              <td>{{ candidate.vote }}</td>
              <td>
                <button type="button" class="btn btn-info btn-sm"
                        data-toggle="modal" data-target="#vote-modal"
                        data-action="{% url 'candidates:vote' candidate.id %}"
                        data-candidate-name="{{ candidate.full_name }}">
                  vote
                </button>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $('#vote-modal').on('show.bs.modal', function (event) {
      var modal = $(this);
      var button = $(event.relatedTarget);
      var action = button.data('action');
      var candidateName = button.data('candidate-name');

      modal.find('#confirm-label').text('Sure to vote for ' + candidateName + '?');
      modal.find('form').attr('action', action)
    })
  </script>
{% endblock %}

candidates/templates/candidates/show.html
{% extends 'base.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <h1>#{{ candidate.id }} {{ candidate.full_name }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td>{{ candidate.full_name }}</td>
          </tr>
          <tr>
            <th scope="row">age</th>
            <td>{{ candidate.age }}</td>
          </tr>
          <tr>
            <th scope="row">politics</th>
            <td>{{ candidate.politics | linebreaks }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <a href="{% url 'candidates:index' %}" class="btn">< Back</a>
      <a href="{% url 'candidates:edit' candidate.id %}" class="btn btn-sm btn-info">Edit</a>
      <a href="{% url 'candidates:delete' candidate.id %}" class="btn btn-sm btn-danger">Delete</a>
    </div>
  </div>
{% endblock %}

core/templates/_form.html
<form action="" method="post">
  {% csrf_token %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" style="margin-top: 10px;">
      {% for error in form.non_field_errors %}
        <strong>{{ error }}</strong>
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form %}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">{{ field.label }}</span>
      </div>
      {{ field }}
    </div>
    {% if field.errors %}
      <div class="alert alert-dismissible alert-danger fade show" style="margin-top: 10px;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ field.label }}錯誤</strong>
        {% for error in field.errors %}
          <p>{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
  {% endfor %}

  <button type="submit" class="btn btn-info float-right">送出</button>
</form>

<style>
  textarea {
    resize: none;
  }
</style>

core/templates/_message.html
{% load message_kind %}

{% if messages %}
  <div class="row">
    <div class="col">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags | message_kind }} alert-dismissible fade show" role="alert">
          <strong>{{ message.tags }}</strong> {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    </div>
  </div>
{% endif %}

core/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Django Vote</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'candidates:index' %}">Candidates</a>
      </li>
    </ul>
  </div>
</nav>

core/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Django Vote{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
      .container {
        margin-top: 30px;
      }
    </style>
    {% block style %}{% endblock %}
  </head>

  <body>
    {% include '_navbar.html' %}

    <div class="container">
      {% include '_message.html' %}
      {% block body %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
  </body>

</html>